### ISSUE TITLE
More convenient path for local fonts

### ISSUE THREAD

**Issue by florian-lefebvre** [rishi-raj-jain/astro-font#12]
Currently the path has to be written like so:
```ts
path: join(process.cwd(), "public", "assets", "fonts", "Deacon-Black.woff2")
```
but it would more convenient to write
```ts
path: join(process.cwd(), "public/assets/fonts/Deacon-Black.woff2")
```
Unfortunately, the following error is thrown:
```
TypeError: n.trim is not a function
    at $i (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro-font/dist/utils.js:7:276728)
    at eval (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro-font/dist/utils.js:8:204)
    at Array.reduce (<anonymous>)
    at _i (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro-font/dist/utils.js:8:168)
    at bd (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro-font/dist/utils.js:8:3289)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Wp (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro-font/dist/utils.js:8:4144)
    at async Promise.all (index 1)
    at async Module.renderChild (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro/dist/runtime/server/render/any.js:14:11)
    at async Object.renderToFinalDestination (D:/DEV/PROJECTS/PRO/satquiztime/satquiz/node_modules/astro/dist/runtime/server/render/util.js:119:7)
```
As a workaround, I can write
```ts
path: join(process.cwd(), ..."public/assets/fonts/Deacon-Black.woff2".split("/"))
```

**Comment by florian-lefebvre** [comment]
Looks like having 2 fonts src using the workaround throws the same error

**Comment by rishi-raj-jain** [comment]
```
path: join(process.cwd(), "public\assets\fonts\Deacon-Black.woff2")
```

can you use this for your system?

**Comment by rishi-raj-jain** [comment]
Continuining this in Discord

**Comment by rishi-raj-jain** [comment]
The n.trim() error seems to be specific to fontkit.
 
Resolved (not related to path), awaiting reproduction / trying out `fontaine` if that works and then re-visit.
